<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Velune.Module.Sample</AssemblyName>
    <RootNamespace>Velune.Module.Sample</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\VELUNE\src\Velune.Module.Abstractions\Velune.Module.Abstractions.csproj"
                      Private="false" />
    <ProjectReference Include="..\..\VELUNE\src\Velune.UI\Velune.UI.csproj"
                      Private="false" />
  </ItemGroup>

</Project>